import {
  WebsiteCategoryType,
  DesignStyle,
} from './plan';

export type MessageSender = 'user' | 'nathan' | 'system';

export interface ChatMessage {
  id: string;
  sender: MessageSender;
  text: string;
  timestamp: number;
  isError?: boolean;
}

export interface N8nChatPayload {
  action: 'sendMessage';
  sessionId: string;
  chatInput: string;
}

/**
 * Website-plan fields Nathan is allowed to update.
 *
 * We intentionally do not let the AI directly control:
 * - estimatedTimeline
 * - estimatedComplexity
 * - suggestedStack
 * - lastUpdated
 *
 * Those remain controlled by Website Tailor.
 */
export interface WebsitePlanUpdate {
  projectName?: string;
  type?: WebsiteCategoryType;
  style?: DesignStyle;
  purpose?: string;
  targetAudience?: string;
  pages?: string[];
  features?: string[];
  designComplexity?: 'Standard' | 'Enhanced' | 'Bespoke';
}

export interface N8nChatResponse {
  output?: string;
  text?: string;
  response?: string;
  message?: string;
  sessionId?: string;

  /**
   * Optional structured changes generated by Nathan.
   */
  planUpdate?: WebsitePlanUpdate;
}

/**
 * Normalized response returned by our n8n service.
 */
export interface NathanResponse {
  text: string;
  planUpdate?: WebsitePlanUpdate;
}

export interface WebhookConfig {
  url: string;
  isCustom: boolean;
  status: 'unconfigured' | 'configured' | 'connected' | 'error';
  lastChecked?: number;
}
